Implementing over commitment
HewlettPackard/squest pull request #106
Opened 2021-08-04 15:27 UTC by a-belhadj

- [ ] Model
- [ ] Forms
- [ ] View (Table in ResourcePool + List Attribute from ResourcePool)
- [ ] Test model
- [ ] Test url
- [ ] Test form

2021-08-05 22:56 UTC, a-belhadj commented
![image](https://user-images.githubusercontent.com/82872898/128431500-2af0189c-7313-42da-86a9-4020f322f0ae.png)
![image](https://user-images.githubusercontent.com/82872898/128431581-503a681d-b2a3-4d17-bf06-bd2b2ad03387.png)
![image](https://user-images.githubusercontent.com/82872898/128431690-cd983762-863c-4f16-87e5-eeed82e89fd6.png)

2021-08-06 08:43 UTC, Sispheor commented on docs/manual/resource_tracking.md
> +If a host has two eight core processors and hyperthreading is enabled, that host will produces thirty-two vCPUs (8 cores x 2processors x 2 threads per core).
then you can configure the over commitment on the CPU produced attribute to `2` to correspond to this behavior.

2021-08-06 08:48 UTC, Sispheor commented on resource_tracker/forms.py
> +                    help_text="Comma-separated list of tags",
Add a section [after this one](https://hewlettpackard.github.io/squest/0.1/manual/resource_tracking/#link-service-catalog-instances-to-resources).
Explain what are tags.

And add a copy of this [tab]( https://django-taggit.readthedocs.io/en/latest/forms.html#tags-in-forms)

2021-08-06 09:00 UTC, Sispheor commented on resource_tracker/views/resource_tracker_graph.py
> +                'display': round(attribute.get_total_consumed(), 2),
round to integer

2021-08-06 09:02 UTC, Sispheor commented on templates/generics/form_edit.html
> +                {{ field.label }}
change help text life resource pool create template

2021-08-06 09:07 UTC, Sispheor requested changes
Some minor change to be done. Overall ok

2021-08-06 14:13 UTC, a-belhadj commented
- [ ] Initial value at creation for over commitment
- [ ] Doc for taggit
- [ ] Round with no decimal
- [ ] Fix delete message on RG/RP (missing <ul> </ul> in RG)
- [ ] Change help text to label below input field
- [ ] Factorize RG/RP form for edit/create 
- [ ] Fix "for" attribute in label tag ( <label for="{{ field.id_for_label }}"...>) Click on label will bring you to the input

2021-08-06 15:04 UTC, Sispheor commented on docs/manual/resource_tracking.md
> +apple ball cat         |``["apple", "ball", "cat"]``     |No commas, so space delimited
Space here after each pipe.  `| word`

2021-08-06 15:18 UTC, Sispheor commented
Very good job done here. Thanks.
Code - Doc - Tests reviewed. All ok.
This is definitely an important feature for the v1.

2021-08-06 15:20 UTC, Sispheor approved these changes

2021-08-06 15:39 UTC, merged