add prod compose file with TLS config
HewlettPackard/squest pull request #139
Opened 2021-09-02 16:11 UTC by Sispheor

2021-09-02 16:24 UTC, a-belhadj commented on Squest/settings/development.py
> +ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
old value was a list and your default value isn't a list. Is it normal ?

2021-09-02 19:12 UTC, a-belhadj commented on docs/deployment.md
> +To run the application, execute the full env docker compose file
"the full env docker compose file"

2021-09-02 19:15 UTC, a-belhadj requested changes

2021-09-02 19:15 UTC, a-belhadj commented on docs/dev/dev-env.md
> +docker-compose -f docker-compose.yml db phpmyadmin rabbitmq up
```
docker-compose up db phpmyadmin rabbitmq
```

2021-09-03 13:01 UTC, Sispheor commented on docs/dev/dev-env.md
> +docker-compose -f docker-compose.yml db phpmyadmin rabbitmq up
Fixed

2021-09-03 13:02 UTC, Sispheor commented
I'll send Ansible deployment with backup in a dedicated PR.
This one contains already a lot of changes.

2021-09-06 07:14 UTC, Sispheor commented
Branch rebased. Ready for review

2021-09-06 08:43 UTC, a-belhadj approved these changes

2021-09-06 08:47 UTC, merged