WIP
HewlettPackard/squest pull request #298
Opened 2021-12-21 15:11 UTC by EliasBoulharts

2021-12-23 16:50 UTC, EliasBoulharts commented
TODO:

2022-01-05 15:06 UTC, Sispheor commented on profiles/models/quota_binding.py
> +        try:
as the limit is tested before. no needs to try catch here

2022-01-05 15:07 UTC, Sispheor commented on profiles/tables/billing_group_table.py
> +        fields = ("name", "actions")
view to be removed

2022-01-05 15:31 UTC, Sispheor commented on profiles/views/quota_attribute_definition_views.py
> +        'details': {'warning_sentence': 'Warning: some users are still present in this quota_attribute_definition:',
Not "users" but attribute definition

2022-01-05 15:34 UTC, Sispheor commented on profiles/views/quota_attribute_definition_views.py
> +        'details': {'warning_sentence': 'Warning: some users are still present in this quota_attribute_definition:',
This quota attribute was linked to the following billing groups (list of billing group)

2022-01-05 17:00 UTC, Sispheor commented on templates/profiles/billing-group-details.html
> +                            <i class="fab fa-cloudscale"></i> Manage attribute and limits
Update the icon with: `<i class="far fa-chart-bar"></i>`

2022-01-05 17:03 UTC, Sispheor commented on templates/sidebar.html
> +                            </li>
Place the quota block before groups as we need to configure this one first.
+ change icon for `<i class="fas fa-chart-pie"></i>`

2022-01-06 13:25 UTC, Sispheor commented on profiles/views/quota_attribute_definition_views.py
> +class QuotaAttributeDefinitionListView(LoginRequiredMixin, SingleTableMixin, FilterView):
admin protected page

2022-01-06 14:07 UTC, Sispheor commented on tests/test_profile/test_quota/test_model.py
> +    def test_consumed_updated_after_billing_group_changed_in_instance(self):
check resource consumption data. We remove 30 vcpu fron one side and we retrieve them on the other side

2022-01-06 14:08 UTC, Sispheor commented on tests/test_profile/test_quota/test_model.py
> +    def test_consumed_updated_after_attribute_definitions_changed_in_quota_attribute(self):
check delta between values

2022-01-06 14:10 UTC, Sispheor commented on profiles/models/quota_binding.py
> +    def available(self):
add test

2022-01-06 14:10 UTC, Sispheor commented on profiles/models/quota_binding.py
> +    def percentage(self):
add test for all cases

2022-01-06 14:11 UTC, Sispheor commented on profiles/models/quota_binding.py
> +    def update_consumed(self):
assert called on update

2022-01-06 14:21 UTC, Sispheor commented
Missing tests:

- [ ] assert called on each signal (from all attached object)
- [ ] test form when overridden save method and/or init method
- [ ] test views (POST) create and edit page

2022-01-06 14:23 UTC, Sispheor requested changes
Some test to be added. Rest is ok.

2022-01-07 10:15 UTC, Sispheor commented on tests/test_profile/test_group/test_group_urls.py
> +        self.client.force_login(self.superuser)
to be removed

2022-01-07 10:25 UTC, Sispheor commented on tests/test_profile/test_quota/test_model.py
> +        self.assertEqual(quota_binding.available, 100 - quota_binding.consumed)
add a test on the "consumed" property

2022-01-07 10:40 UTC, Sispheor commented on tests/test_profile/test_quota/test_urls.py
> +        url = reverse('profiles:quota_attribute_definition_list')
add a check on returned data

2022-01-07 10:40 UTC, Sispheor requested changes
More tests to be added.

2022-01-07 14:08 UTC, Sispheor commented on tests/test_profile/test_quota/test_model.py
> +        for instance in self.test_billing_group.instances.all():
add local object with hard coded values and then check

2022-01-07 14:11 UTC, Sispheor requested changes
Ultimate last test to be added

2022-01-07 14:55 UTC, merged