Add requester permissions
HewlettPackard/squest pull request #689
Opened 2023-09-27 13:39 UTC by a-belhadj

2023-09-27 16:22 UTC, EliasBoulharts commented on tests/test_profiles/test_model/test_has_perm_for_owner.py
> +    def __test_has_perm_generic_with_requester_perm_user_permission(self, obj, action):
2x _

2023-09-27 16:27 UTC, EliasBoulharts requested changes
change requesterpermission to ownerpermission and rename user field in request to requester + generate a new migration

2023-09-29 08:21 UTC, Sispheor commented on tests/test_profiles/test_model/test_get_queryset_instance.py
> +        # add global perm
owner perm

2023-09-29 08:23 UTC, Sispheor commented on tests/test_profiles/test_model/test_get_queryset_request.py
> +        # add global perm
owner

2023-09-29 08:24 UTC, Sispheor commented on tests/test_profiles/test_model/test_get_queryset_support.py
> +        # add global perm
owner

2023-09-29 08:53 UTC, EliasBoulharts approved these changes

2023-09-29 08:54 UTC, Sispheor approved these changes

2023-09-29 08:58 UTC, merged