add permission on operation
HewlettPackard/squest pull request #803
Opened 2024-12-13 14:52 UTC by Sispheor

- Fix UI
- add perm on operation
- bulk perm update from service page and portfolio page
- drop compose v2 support

#724

2024-12-13 15:23 UTC, EliasBoulharts approved these changes

2024-12-13 16:07 UTC, a-belhadj commented on dev.docker-compose.yml
>  services:
CHANGELOG Breaking changes does not support docker compose v1 anymore

2024-12-13 16:09 UTC, a-belhadj commented on service_catalog/forms/form_utils.py
> +import inspect
?

2024-12-13 16:16 UTC, a-belhadj commented on service_catalog/models/instance.py
> +        if self.service is None:
service shouldn't be None, it should be required in Instance

2024-12-13 16:19 UTC, a-belhadj commented on service_catalog/views/instance.py
> +from gc import enable
?

2024-12-13 16:28 UTC, a-belhadj commented on tests/test_service_catalog/test_forms/test_admin_service_forms.py
> +                "permission": FormUtils.get_default_permission_for_operation(),
Three times the same

2024-12-13 16:32 UTC, a-belhadj requested changes
small changes to do before merge

2024-12-16 10:21 UTC, a-belhadj approved these changes

2024-12-16 10:21 UTC, merged